/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "EZI2C.h"
#include "EZI2C_PINS.h"
#include "EZI2C_PVT.h"
#include "EZI2C_EZI2C.h"
#include "EZI2C_EZI2C_PVT.h"
#include "EZI2C_BOOT.h"
#include "Button1.h"
#include "Button1_aliases.h"
#include "Button2.h"
#include "Button2_aliases.h"
#include "Button3.h"
#include "Button3_aliases.h"
#include "Button4.h"
#include "Button4_aliases.h"
#include "LCD.h"
#include "LED1.h"
#include "LED1_aliases.h"
#include "LED2.h"
#include "LED2_aliases.h"
#include "LED3.h"
#include "LED3_aliases.h"
#include "LED4.h"
#include "LED4_aliases.h"
#include "LEDreg.h"
#include "Cheat.h"
#include "Cheat_aliases.h"
#include "LED_AWAKE.h"
#include "LED_AWAKE_aliases.h"
#include "ADC.h"
#include "SpeedPin.h"
#include "SpeedPin_aliases.h"
#include "BUZZER.h"
#include "BUZZER_aliases.h"
#include "Clock_1.h"
#include "PWM_Fail.h"
#include "isr_sleep.h"
#include "isr_fail.h"
#include "Button_Reg.h"
#include "PWM_Pass.h"
#include "Clock_2.h"
#include "Sleep_Reg.h"
#include "Clock_3.h"
#include "LED_B.h"
#include "LED_B_aliases.h"
#include "LED_G.h"
#include "LED_G_aliases.h"
#include "LED_R.h"
#include "LED_R_aliases.h"
#include "EZI2C_SCBCLK.h"
#include "EZI2C_sda.h"
#include "EZI2C_sda_aliases.h"
#include "EZI2C_scl.h"
#include "EZI2C_scl_aliases.h"
#include "EZI2C_SCB_IRQ.h"
#include "LCD_LCDPort.h"
#include "LCD_LCDPort_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"
#include "cy_em_eeprom.h"

/*[]*/

