/*******************************************************************************
 * File Name: project.h
 * cydsfit No Version Information Found
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <EEPROM.h>
#include <LCD.h>
#include <I2C.h>
#include <I2C_I2C.h>
#include <I2C_PINS.h>
#include <I2C_I2C_PVT.h>
#include <I2C_PVT.h>
#include <LED1.h>
#include <LED1_aliases.h>
#include <LED2.h>
#include <LED2_aliases.h>
#include <LED3.h>
#include <LED3_aliases.h>
#include <LED4.h>
#include <LED4_aliases.h>
#include <Start.h>
#include <Start_aliases.h>
#include <LEDreg.h>
#include <ResetHS.h>
#include <ResetHS_aliases.h>
#include <Max.h>
#include <Max_aliases.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <I2C_SCB_IRQ.h>
#include <I2C_SCBCLK.h>
#include <I2C_scl.h>
#include <I2C_scl_aliases.h>
#include <I2C_sda.h>
#include <I2C_sda_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

